### ISSUE TITLE
Implement all player weapons

### ISSUE THREAD

**Issue by simonakosrobert** [simonakosrobert/Platypus-Remastered-Unity#3]
The task is to implement all of the avaible weapons the player can acquire and also their stars.

# Tasks
- [ ] Add Automatic machine gun
- [ ] Add Wide gun
- [ ] Add Sonic pulse
- [ ] Add Rocket gun
- [ ] Add Lightning gun
