### ISSUE TITLE
Implement pause menu

### ISSUE THREAD

**Issue by simonakosrobert** [simonakosrobert/Platypus-Remastered-Unity#5]
# Tasks
- [x] Create and add pause menu screen
- [ ] Add "resume", "settings" and "quit to main menu" buttons
- [ ] Implement functions for the buttons
